// Xibo player Rust implementation, (c) 2022-2024 Georg Brandl.
// Licensed under the GNU AGPL, version 3 or later.

//! Main entry point for the application.

pub mod config;
pub mod mainloop;
pub mod server;
pub mod resource;
pub mod schedule;
pub mod layout;
pub mod xmds;
pub mod xmr;
pub mod command;
pub mod logger;
pub mod util;
pub mod gui;
pub mod stats;
pub mod criteria;
pub mod faults;
pub mod adspace;
pub mod syncgroup;

use std::path::PathBuf;
use std::sync::{Arc, Mutex};
use anyhow::{ensure, Context};
use clap::Parser;

#[derive(Parser)]
#[command(author, version, about)]
#[command(help_template = "by {author}{about-section}\n{usage-heading} {usage}\n\n{all-args}")]
struct Args {
    /// The directory to place config files and cached content.
    envdir: PathBuf,
    /// The CMS host including scheme, e.g. https://xibo.example.com/
    #[arg(long)]
    host: Option<String>,
    /// The CMS secret key.
    #[arg(long)]
    key: Option<String>,
    /// The ID for this display, autogenerated if omitted.
    #[arg(long)]
    display_id: Option<String>,
    /// The initial name for this display.
    #[arg(long)]
    display_name: Option<String>,
    /// URL for a proxy server for HTTP/XMDS requests.
    #[arg(long)]
    proxy: Option<String>,
    /// Specify the screen to show Arexibo on.
    /// Can be a number (starting from 1) or a name.  For a list of
    /// screens currently connected, pass "list".
    #[arg(long)]
    screen: Option<String>,
    /// Show web inspector to debug layout problems.
    #[arg(long)]
    inspect: bool,
    /// Enable debug logging of WebEngine messages: prints every JS
    /// `console.*` message from every frame (main layout, overlay, and
    /// every widget iframe alike) to this player's own log output, plus
    /// a handful of the player's own diagnostic console.log calls
    /// (`arexibo-show:`/`arexibo-shrink:`) that are otherwise silent --
    /// also still sets Chromium's own verbose logging flags. Off by
    /// default since this adds a fair amount of noise; useful when
    /// troubleshooting why a widget isn't rendering/showing correctly.
    #[arg(long)]
    web_debug: bool,
    /// Clear the local file cache and re-download any files.
    #[arg(long)]
    clear: bool,
    /// Enable debug logging.
    #[arg(long)]
    debug: bool,
    /// Disable HTTPS certificate verification.
    #[arg(long)]
    no_verify: bool,
    /// Allow starting and running without connection to the CMS,
    /// showing the last cached schedule.
    #[arg(long)]
    allow_offline: bool,
}

fn main() {
    log::set_logger(&logger::Logger).expect("failed to set logger");
    log::set_max_level(log::LevelFilter::Debug);
    if let Err(e) = main_inner() {
        // Exit code 2: display not authorized yet.
        //
        // As of the pending-authorization feature (Handler::pending_auth
        // in mainloop.rs), this no longer occurs during normal
        // operation -- an unauthorized display now stays running,
        // showing the splash screen, and retries on its own. Kept as a
        // defensive fallback (harmless if never triggered) in case
        // NotAuthorized is ever raised again for another reason.
        //
        // Exit code 1: actual error (bad config, CMS unreachable, etc.)
        if e.root_cause().downcast_ref::<mainloop::NotAuthorized>().is_some() {
            log::warn!("{:#}", e);
            std::process::exit(2);
        }
        log::error!("exiting on error: {:#}", e);
        std::process::exit(1);
    }
}

fn main_inner() -> anyhow::Result<()> {
    let args = Args::parse();

    log::info!("Arexibo {} starting up...", clap::crate_version!());

    if args.debug {
        log::set_max_level(log::LevelFilter::Debug);
    } else {
        log::set_max_level(log::LevelFilter::Info);
    }

    // check environment directory argument
    ensure!(args.envdir.exists(), "environment directory '{}' does not exist",
            args.envdir.display());
    let cmscfg = args.envdir.join("cms.json");

    // check if we have a CMS config either stored, or given with arguments
    let cms = if let Some((address, key)) = args.host.zip(args.key) {
        let display_id = args.display_id.unwrap_or_else(util::get_display_id);
        config::CmsSettings { address, key, display_id,
                              display_name: args.display_name,
                              proxy: args.proxy }
    } else if let Ok(from_json) = config::CmsSettings::from_file(&cmscfg) {
        from_json
    } else {
        anyhow::bail!("cms.json not found or invalid, run with the --host and --key \
                       options to reconfigure");
    };

    cms.to_file(&cmscfg).context("writing new CMS config")?;

    // create the backend handler and required channels
    let (togui_tx, togui_rx) = crossbeam_channel::bounded(5);
    let (fromgui_tx, fromgui_rx) = crossbeam_channel::bounded(5);
    // Interactive Control duration overrides (/duration/set|extend|expire,
    // see server.rs) come in on the HTTP server's own thread pool and
    // need to be relayed to the mainloop, which is the only place that
    // can turn them into JS run in the currently-displayed page.
    let (duration_tx, duration_rx) = crossbeam_channel::bounded(20);
    // Same reasoning as duration_tx/duration_rx, for Interactive
    // Control webhook triggers (/trigger, see server.rs's own
    // TriggerRequest).
    let (trigger_tx, trigger_rx) = crossbeam_channel::bounded(20);

    let mut handler = mainloop::Handler::new(&cms, args.clear, &args.envdir, args.no_verify,
                                              args.allow_offline, args.debug,
                                              togui_tx, fromgui_rx, duration_rx, trigger_rx)
        .context("creating backend handler")?;
    let mut settings = handler.player_settings();

    // apply setting to inhibit screensaver
    if settings.prevent_sleep {
        if let Err(e) = util::inhibit_screensaver() {
            log::warn!("could not inhibit screensaver: {:#}", e);
        }
    }

    // Create the internal webserver on the requested port.
    // Shared across the main server AND every shard below (see
    // server::LocalDataStore's own doc comment) -- a single, genuinely
    // shared store, not one per shard.
    let local_data: server::LocalDataStore = std::sync::Arc::new(std::sync::Mutex::new(
        std::collections::HashMap::new()));
    // Only the main server's own bind address is affected by
    // embedded_server_allow_wan (for /trigger reachability from
    // outside the display, see Interactive Control's own webhook
    // feature) -- the per-widget shards below stay loopback-only
    // regardless, since they exist purely to work around Chromium's
    // 6-connections-per-origin limit for internal widget loading, not
    // for external reachability.
    // Respect the CMS's own embeddedServerPort setting (an admin can
    // configure this from the Display Profile) if it sent a real,
    // non-zero value -- our own fixed constant is only a fallback for
    // a CMS that doesn't specify anything. Note for whoever deploys
    // this: this is a *behavior change* from before, when the CMS's
    // own value was silently ignored -- an existing fleet may switch
    // from EMBEDDED_SERVER_PORT to whatever the CMS says on next
    // restart after upgrading, which matters if anything external
    // (firewall rules, port forwarding, monitoring) assumed the old
    // fixed port specifically.
    let bind_addr = if settings.embedded_server_allow_wan { "0.0.0.0" } else { "127.0.0.1" };
    let port = server::effective_port(settings.embedded_server_port);
    let webserver = server::Server::new(args.envdir.join("res"), bind_addr, port,
                                         duration_tx.clone(), trigger_tx.clone(), local_data.clone())
        .context("creating internal HTTP server")?;
    settings.embedded_server_port = webserver.port();
    let shard_port = webserver.port();
    handler.set_html_port(shard_port);
    webserver.start_pool();

    // Additional listeners, same port, different loopback addresses,
    // all serving the same directory -- see HTML_SHARD_COUNT's own doc
    // comment (Chromium's 6-connections-per-origin limit). write_media
    // picks a shard per widget deterministically from its id; 127.0.0.1
    // (set up above, shard 1) handles top-level navigation, shards
    // 2..=HTML_SHARD_COUNT get their own listener here.
    //
    // Skipped entirely when the main server is bound to 0.0.0.0
    // (embedded_server_allow_wan): a wildcard listener already accepts
    // connections addressed to *every* local address on that port,
    // including 127.0.0.2/.3/.4 -- binding those separately would
    // always conflict with the already-listening wildcard socket
    // (confirmed from a real report: "Address already in use (os error
    // 98)" on startup, every single time, as soon as WAN access got
    // enabled). The wildcard socket alone already serves every shard
    // address correctly, no separate listeners needed.
    if bind_addr != "0.0.0.0" {
        for shard in 2..=server::HTML_SHARD_COUNT {
            let addr = format!("127.0.0.{shard}");
            let shard_server = server::Server::new(args.envdir.join("res"), &addr, shard_port,
                                                     duration_tx.clone(), trigger_tx.clone(), local_data.clone())
                .with_context(|| format!("creating internal HTTP server shard on {addr}"))?;
            shard_server.start_pool();
        }
    }

    // BUG fix (found from a real report: a totem got stuck showing
    // only the splash screen forever after a hard power-cut, with
    // "doing collection" never once appearing in the log -- strongly
    // suggesting this thread panicked, or run() otherwise returned,
    // almost immediately after starting, likely from a corrupted
    // cached file on disk left by the abrupt power loss). run()'s own
    // `loop { select! {...} }` has no explicit break/return -- it's
    // designed to run forever, so ANY return (an Err bubbling up via
    // `?` from deep inside a single collection cycle, or even an Ok,
    // which shouldn't normally happen at all) represents an unexpected
    // exit. Previously, this thread's own JoinHandle was never
    // checked, and a panic inside it unwinds *only that thread*,
    // silently -- the GUI thread keeps running with whatever was on
    // screen at that moment (here, just the splash), forever, with no
    // further collection ever happening again and no clear signal
    // anywhere that this occurred. Wrapping in catch_unwind and
    // exiting the whole process on either outcome means systemd's own
    // `Restart=always` (see arexibo.service) gives a genuinely fresh
    // start instead -- the same recovery this whole codebase already
    // relies on elsewhere (e.g. the QtWebEngine renderProcessTerminated
    // handler, gui/view.h) for exactly this class of "can't safely
    // continue, but a full restart fixes it" problem.
    //
    // Exiting via std::process::exit() directly from *this* thread,
    // while gui::run()'s own Qt event loop (on the main thread, below)
    // is still fully active, was causing a real, reproducible segfault
    // on shutdown -- Qt/Chromium never got a chance to tear down their
    // own internal state (GPU process, IPC channels to Chromium
    // subprocesses) before the whole process vanished out from under
    // them. Instead: record the exit code here, ask Qt to quit its own
    // event loop cleanly (gui::quit(), thread-safe by Qt's own design),
    // and let the main thread -- once gui::run() actually returns
    // below, meaning Qt's own teardown has already happened -- be the
    // one that calls std::process::exit(), with nothing left running
    // that could object to it.
    let exit_code = Arc::new(Mutex::new(1));
    let exit_code_for_thread = exit_code.clone();
    std::thread::spawn(move || {
        let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| handler.run()));
        log::error!("{}", mainloop_exit_message(&result));
        *exit_code_for_thread.lock().unwrap() = mainloop_exit_code(&result);
        gui::quit();
    });

    gui::run(settings, args.screen.unwrap_or_default(), args.inspect,
             args.web_debug, togui_rx, fromgui_tx);
    // gui::run() (cpp::run(), QApplication::exec()) has now returned --
    // Qt's own event loop exited cleanly via gui::quit() above, so
    // nothing is left running that a process-wide exit could disrupt.
    std::process::exit(*exit_code.lock().unwrap());
}

/// Determines the log message for the mainloop thread's own exit
/// (whichever of the three ways it happened) -- extracted as its own
/// pure function specifically so this can be unit-tested directly,
/// without needing to actually spawn a thread or call
/// std::process::exit (which would kill the test runner itself).
fn mainloop_exit_message(result: &std::thread::Result<anyhow::Result<()>>) -> String {
    match result {
        Ok(Ok(())) => "mainloop thread exited normally (unexpected -- it's designed \
                       to run forever) -- exiting so systemd can restart cleanly".to_string(),
        Ok(Err(e)) => format!("mainloop thread exited with an error: {e:#} -- \
                               exiting so systemd can restart cleanly"),
        Err(_) => "mainloop thread panicked -- exiting so systemd can restart \
                   cleanly".to_string(),
    }
}

/// Determines the process exit code for the mainloop thread's own
/// exit -- same testable-pure-function reasoning as
/// mainloop_exit_message. Exit code 3 specifically for
/// RestartRequired (see its own doc comment in mainloop.rs): an
/// intentional exit so the supervisor restarts us fresh to rebind the
/// embedded webserver's own TCP listener, not a genuine error. Every
/// other case (a real error, a panic, or the unexpected "exited
/// normally") uses exit code 1.
fn mainloop_exit_code(result: &std::thread::Result<anyhow::Result<()>>) -> i32 {
    if let Ok(Err(e)) = result {
        if e.root_cause().downcast_ref::<mainloop::RestartRequired>().is_some() {
            return 3;
        }
    }
    1
}

#[cfg(test)]
mod mainloop_exit_message_tests {
    use super::mainloop_exit_message;

    #[test]
    fn describes_a_panic_distinctly() {
        let result: std::thread::Result<anyhow::Result<()>> = Err(Box::new("boom"));
        let msg = mainloop_exit_message(&result);
        assert!(msg.contains("panicked"), "got: {msg}");
    }

    #[test]
    fn describes_an_error_return_with_its_own_message() {
        let result: std::thread::Result<anyhow::Result<()>> =
            Ok(Err(anyhow::anyhow!("network is unreachable")));
        let msg = mainloop_exit_message(&result);
        assert!(msg.contains("network is unreachable"),
                "the underlying error's own message must be included -- got: {msg}");
        assert!(!msg.contains("panicked"));
    }

    #[test]
    fn describes_an_unexpected_normal_return_distinctly() {
        let result: std::thread::Result<anyhow::Result<()>> = Ok(Ok(()));
        let msg = mainloop_exit_message(&result);
        assert!(msg.contains("unexpected"), "got: {msg}");
        assert!(!msg.contains("panicked"));
    }
}

#[cfg(test)]
mod mainloop_exit_code_tests {
    use super::mainloop_exit_code;

    #[test]
    fn restart_required_gets_its_own_distinct_exit_code() {
        // Wrapping the real marker type, not just an anyhow!() with a
        // similar-looking message -- must match via root_cause's own
        // downcast, not string comparison.
        let result: std::thread::Result<anyhow::Result<()>> =
            Ok(Err(anyhow::Error::new(crate::mainloop::RestartRequired)));
        assert_eq!(mainloop_exit_code(&result), 3);
    }

    #[test]
    fn a_genuine_error_gets_the_generic_exit_code() {
        let result: std::thread::Result<anyhow::Result<()>> =
            Ok(Err(anyhow::anyhow!("network is unreachable")));
        assert_eq!(mainloop_exit_code(&result), 1);
    }

    #[test]
    fn a_panic_gets_the_generic_exit_code() {
        let result: std::thread::Result<anyhow::Result<()>> = Err(Box::new("boom"));
        assert_eq!(mainloop_exit_code(&result), 1);
    }

    #[test]
    fn an_unexpected_normal_return_gets_the_generic_exit_code() {
        let result: std::thread::Result<anyhow::Result<()>> = Ok(Ok(()));
        assert_eq!(mainloop_exit_code(&result), 1);
    }
}
