// Xibo player Rust implementation, (c) 2022-2024 Georg Brandl.
// Licensed under the GNU AGPL, version 3 or later.

//! Main entry point for the application.

pub mod config;
pub mod mainloop;
pub mod server;
pub mod resource;
pub mod schedule;
pub mod layout;
pub mod xmds;
pub mod xmr;
pub mod command;
pub mod logger;
pub mod util;
pub mod gui;
pub mod stats;
pub mod criteria;
pub mod faults;
pub mod adspace;

use std::path::PathBuf;
use anyhow::{ensure, Context};
use clap::Parser;

#[derive(Parser)]
#[command(author, version, about)]
#[command(help_template = "by {author}{about-section}\n{usage-heading} {usage}\n\n{all-args}")]
struct Args {
    /// The directory to place config files and cached content.
    envdir: PathBuf,
    /// The CMS host including scheme, e.g. https://xibo.example.com/
    #[arg(long)]
    host: Option<String>,
    /// The CMS secret key.
    #[arg(long)]
    key: Option<String>,
    /// The ID for this display, autogenerated if omitted.
    #[arg(long)]
    display_id: Option<String>,
    /// The initial name for this display.
    #[arg(long)]
    display_name: Option<String>,
    /// URL for a proxy server for HTTP/XMDS requests.
    #[arg(long)]
    proxy: Option<String>,
    /// Specify the screen to show Arexibo on.
    /// Can be a number (starting from 1) or a name.  For a list of
    /// screens currently connected, pass "list".
    #[arg(long)]
    screen: Option<String>,
    /// Show web inspector to debug layout problems.
    #[arg(long)]
    inspect: bool,
    /// Enable debug logging of WebEngine messages: prints every JS
    /// `console.*` message from every frame (main layout, overlay, and
    /// every widget iframe alike) to this player's own log output, plus
    /// a handful of the player's own diagnostic console.log calls
    /// (`arexibo-show:`/`arexibo-shrink:`) that are otherwise silent --
    /// also still sets Chromium's own verbose logging flags. Off by
    /// default since this adds a fair amount of noise; useful when
    /// troubleshooting why a widget isn't rendering/showing correctly.
    #[arg(long)]
    web_debug: bool,
    /// Clear the local file cache and re-download any files.
    #[arg(long)]
    clear: bool,
    /// Enable debug logging.
    #[arg(long)]
    debug: bool,
    /// Disable HTTPS certificate verification.
    #[arg(long)]
    no_verify: bool,
    /// Allow starting and running without connection to the CMS,
    /// showing the last cached schedule.
    #[arg(long)]
    allow_offline: bool,
}

fn main() {
    log::set_logger(&logger::Logger).expect("failed to set logger");
    log::set_max_level(log::LevelFilter::Debug);
    if let Err(e) = main_inner() {
        // Exit code 2: display not authorized yet.
        //
        // NOTE: as of the pending-authorization feature (see
        // mainloop.rs's `Handler::pending_auth`), this specific error
        // no longer occurs during normal operation -- an unauthorized
        // display now stays running, showing the splash screen with
        // this machine's own hostname/IP, and retries registration
        // periodically on its own, rather than exiting for systemd's
        // `Restart=` to relaunch it from scratch every time. This check
        // is kept as a defensive fallback (harmless if never triggered)
        // rather than removed outright, in case `NotAuthorized` is ever
        // raised again for some other reason in the future.
        //
        // Exit code 1: actual error (bad config, CMS unreachable, etc.)
        if e.root_cause().downcast_ref::<mainloop::NotAuthorized>().is_some() {
            log::warn!("{:#}", e);
            std::process::exit(2);
        }
        log::error!("exiting on error: {:#}", e);
        std::process::exit(1);
    }
}

fn main_inner() -> anyhow::Result<()> {
    let args = Args::parse();

    log::info!("Arexibo {} starting up...", clap::crate_version!());

    if args.debug {
        log::set_max_level(log::LevelFilter::Debug);
    } else {
        log::set_max_level(log::LevelFilter::Info);
    }

    // check environment directory argument
    ensure!(args.envdir.exists(), "environment directory '{}' does not exist",
            args.envdir.display());
    let cmscfg = args.envdir.join("cms.json");

    // check if we have a CMS config either stored, or given with arguments
    let cms = if let Some((address, key)) = args.host.zip(args.key) {
        let display_id = args.display_id.unwrap_or_else(util::get_display_id);
        config::CmsSettings { address, key, display_id,
                              display_name: args.display_name,
                              proxy: args.proxy }
    } else if let Ok(from_json) = config::CmsSettings::from_file(&cmscfg) {
        from_json
    } else {
        anyhow::bail!("cms.json not found or invalid, run with the --host and --key \
                       options to reconfigure");
    };

    cms.to_file(&cmscfg).context("writing new CMS config")?;

    // create the backend handler and required channels
    let (togui_tx, togui_rx) = crossbeam_channel::bounded(5);
    let (fromgui_tx, fromgui_rx) = crossbeam_channel::bounded(5);
    // Interactive Control duration overrides (/duration/set|extend|expire,
    // see server.rs) come in on the HTTP server's own thread pool and
    // need to be relayed to the mainloop, which is the only place that
    // can turn them into JS run in the currently-displayed page.
    let (duration_tx, duration_rx) = crossbeam_channel::bounded(20);

    let mut handler = mainloop::Handler::new(&cms, args.clear, &args.envdir, args.no_verify,
                                              args.allow_offline, args.debug,
                                              togui_tx, fromgui_rx, duration_rx)
        .context("creating backend handler")?;
    let mut settings = handler.player_settings();

    // apply setting to inhibit screensaver
    if settings.prevent_sleep {
        if let Err(e) = util::inhibit_screensaver() {
            log::warn!("could not inhibit screensaver: {:#}", e);
        }
    }

    // Create the internal webserver on the requested port.
    // Shared across the main server AND every shard below (see
    // server::LocalDataStore's own doc comment) -- a single, genuinely
    // shared store, not one per shard.
    let local_data: server::LocalDataStore = std::sync::Arc::new(std::sync::Mutex::new(
        std::collections::HashMap::new()));
    let webserver = server::Server::new(args.envdir.join("res"), "127.0.0.1",
                                         server::EMBEDDED_SERVER_PORT,
                                         duration_tx.clone(), local_data.clone())
        .context("creating internal HTTP server")?;
    settings.embedded_server_port = webserver.port();
    let shard_port = webserver.port();
    handler.set_html_port(shard_port);
    webserver.start_pool();

    // Additional listeners, same port, different loopback addresses, all
    // serving the exact same directory -- see server::HTML_SHARD_COUNT's
    // own doc comment for why (Chromium's hardcoded 6-connections-per-
    // origin limit; a single layout can easily have more than 6
    // simultaneous `render="html"` iframe widgets, each its own HTTP
    // request, and this compounds further whenever an overlay is also
    // showing such widgets at the same time -- a real report: main
    // layout content intermittently missing/delayed, but only while an
    // overlay was also active). `layout.rs::write_media` picks one of
    // these shards per widget (deterministically, from the widget's own
    // id) for every `render="html"` iframe's own `src`, spreading
    // connection load across `HTML_SHARD_COUNT` independent pools
    // regardless of which view(s) are currently active -- the `127.0.0.1`
    // pool set up just above (used for each view's own top-level
    // navigation, and implicitly shard 1) is one of them; loopback
    // addresses 2..=HTML_SHARD_COUNT get their own dedicated listener
    // here.
    for shard in 2..=server::HTML_SHARD_COUNT {
        let addr = format!("127.0.0.{shard}");
        let shard_server = server::Server::new(args.envdir.join("res"), &addr, shard_port,
                                                 duration_tx.clone(), local_data.clone())
            .with_context(|| format!("creating internal HTTP server shard on {addr}"))?;
        shard_server.start_pool();
    }

    std::thread::spawn(|| handler.run());

    gui::run(settings, args.screen.unwrap_or_default(), args.inspect,
             args.web_debug, togui_rx, fromgui_tx);
    Ok(())
}
