// Xibo player Rust implementation, (c) 2022-2024 Georg Brandl.
// Licensed under the GNU AGPL, version 3 or later.

//! Send SOAP requests to the XMDS endpoint.

/// Includes the SOAP glue code generated by build.rs.
mod soap {
    #![allow(non_snake_case)]
    include!(concat!(env!("OUT_DIR"), "/xmds_soap.rs"));
}

use std::{collections::HashMap, fs, path::PathBuf};
use anyhow::{ensure, Context, Result};
use elementtree::Element;
use serde::Serialize;
use crate::config::{CmsSettings, PlayerSettings};
use crate::command::Command;
use crate::util::{TIME_FMT, Base64Field, ElementExt, retrieve_mac, get_display_name};
use crate::resource::ReqFile;
use crate::schedule::Schedule;
use crate::logger::LogEntry;

/// XMDS endpoint version -- each version is a separate server-side
/// handler (Soap5.php, Soap6.php...), so v6/v7-only methods
/// (GetWeather/GetDependency/GetData) always fail against v5.
///
/// CMS v4+'s Data Widget JSON/HTML splitting is also gated by this
/// version, not by clientType/clientCode -- v5 just doesn't generate
/// those entries, which is why Data Widgets currently work via the
/// embedded-HTML path. The player-side GetData integration this would
/// require (discovery, independent polling, atomic writes, GUI
/// reload notification, downloading files[] entries, retry backoff,
/// pruning against the active schedule, coordination with the
/// XMR-pushed dataUpdate path) is done and verified against a real
/// CMS -- staying on v5 here is a deliberate choice, not a missing
/// prerequisite. See the project's own status document for the
/// current reasoning on when to actually bump this.
const XMDS_ENDPOINT_VERSION: u32 = 5;

/// Whether the endpoint has GetWeather/GetDependency/GetData -- lets
/// callers skip a call known to always fail.
pub fn xmds_supports_v6_v7_methods() -> bool {
    XMDS_ENDPOINT_VERSION >= 6
}

/// Proxy for the XMDS calls to the CMS.
pub struct Cms {
    service: soap::Service,
    xml_dir: PathBuf,
    display_name: String,
    mac_addr: String,
    channel: String,
    cms_key: String,
    hw_key: String,
    pub_key: String,
    /// Precomputed once at construction (see CmsSettings's own
    /// `default_xmr_websocket_address` doc comment for why this
    /// exists) -- used as a fallback candidate in register_display()
    /// when the CMS sends an empty xmrWebSocketAddress.
    default_ws_address: Option<String>,
}

impl Cms {
    pub fn new(cms: &CmsSettings, pub_key: String, no_verify: bool, xml_dir: PathBuf) -> Result<Self> {
        Ok(Self {
            service: soap::Service::new(format!("{}/xmds.php?v={XMDS_ENDPOINT_VERSION}", cms.address),
                                        cms.make_agent(no_verify)?),
            display_name: cms.display_name.as_ref().map_or_else(get_display_name,
                                                                |name| name.to_owned()),
            mac_addr: retrieve_mac().unwrap_or_else(|| "00:00:00:00:00:00".into()),
            channel: cms.xmr_channel(),
            cms_key: cms.key.clone(),
            hw_key: cms.display_id.clone(),
            pub_key,
            default_ws_address: cms.default_xmr_websocket_address(),
            xml_dir,
        })
    }

    pub fn register_display(&mut self) -> Result<Option<PlayerSettings>> {
        // Temporary diagnostic knob (found genuinely useful investigating
        // a real report: XMR WebSocket connection closing almost
        // immediately after connecting on CMS 4.5 with "Invalid key" in
        // the XMR relay's own log -- confirmed via the relay's real
        // source code that key validation depends entirely on a
        // per-instance key having been registered via `addKey()`
        // beforehand, seemingly never wired up for the brand new
        // (March 2026) linux WebSocket XMR support path specifically).
        // Lets us test whether reporting as clientType "windows"
        // (an older, more mature WebSocket XMR code path) hits a
        // *working* addKey()-registration path on the CMS side, without
        // needing a real Windows machine to compare against. NOT meant
        // to be left set permanently -- this misrepresents the player to
        // the CMS, which could affect other clientType-conditional CMS
        // behavior in ways beyond just this specific XMR question.
        let fake_client_type = std::env::var("AREXIBO_FAKE_CLIENTTYPE").ok();
        let (client_type, client_code, operating_system): (&str, i64, &str) =
            match fake_client_type.as_deref() {
                Some("windows") => {
                    log::info!("overriding clientType to \"windows\" via \
                                AREXIBO_FAKE_CLIENTTYPE (diagnostic only)");
                    ("windows", 407, "windows")
                }
                Some(other) if !other.is_empty() => {
                    log::warn!("AREXIBO_FAKE_CLIENTTYPE={other:?} not a supported \
                                override value, ignoring (only \"windows\" is \
                                implemented) -- using real clientType \"linux\"");
                    ("linux", 407, "linux")
                }
                _ => ("linux", 407, "linux"),
            };
        let xml = self.service.RegisterDisplay(
            soap::RegisterDisplayRequest {
                serverKey: &self.cms_key,
                hardwareKey: &self.hw_key,
                displayName: &self.display_name,
                clientType: client_type,
                clientVersion: clap::crate_version!(),
                clientCode: client_code,
                operatingSystem: operating_system,
                macAddress: &self.mac_addr,
                xmrChannel: &self.channel,
                xmrPubKey: &self.pub_key,
            }
        ).context("registering display")?.ActivationMessage;
        let _ = fs::write(self.xml_dir.join("register.xml"), &xml);

        let tree = Element::from_reader(&mut xml.as_bytes()).context("parsing activation message")?;
        let code = tree.get_attr("code").context("no result code in activation")?;
        if code != "READY" {
            Ok(None)
        } else {
            let mut commands = HashMap::new();
            for cmds in tree.find_all("commands") {
                for el in cmds.children() {
                    commands.insert(el.tag().name().into(),
                                    Command {
                                        command: el.parse_child("commandString")?,
                                        validate: el.def_child("validationString", "")?,
                                        alerts: el.def_child("createAlertOn", "")?,
                                    });
                }
            }
            // only try websocket if the CMS lets us use it
            //
            // Manual override (found from a real report: the CMS
            // consistently wiped a manually-fixed WebSocket address on
            // *every single* successful registration against a CMS
            // 4.5.0 -- not a rare, transient hiccup as originally
            // assumed in section 64's own fix/warning, but a
            // reproducible pattern, reinforcing that the CMS's own
            // isWebSocketXmrSupported() check (lib/Xmds/Soap5.php) is
            // unreliable in practice for at least some real
            // deployments on this CMS version -- consistent with it
            // being a brand-new, narrowly-tested feature (merged March
            // 2026, per the CMS's own PR history). Since we can't fix
            // the CMS's own check from here, this gives an affected
            // deployment a way to simply stop trusting it: if set, this
            // always wins, regardless of what the CMS's xmrType says on
            // any given registration -- the CMS can no longer silently
            // wipe an address the operator has confirmed works.
            let forced_ws = std::env::var("AREXIBO_FORCE_WS_ADDRESS").ok()
                                      .filter(|s| !s.is_empty());
            let xmr_type: String = tree.def_child("xmrType", "zmq")?;
            // The CMS's own raw, verbatim value -- empty if the CMS
            // didn't send WebSocket XMR support at all (xmrType != ws)
            // or sent an empty address either way. Deliberately
            // independent of AREXIBO_FORCE_WS_ADDRESS and the /xmr
            // fallback below -- neither of those came from the CMS
            // itself, so neither belongs in this field. See
            // PlayerSettings::xmr_web_socket_address_in_use's own doc
            // comment for why this distinction exists as two separate
            // fields rather than one.
            let xmr_web_socket_address = if &xmr_type == "ws" {
                tree.def_child("xmrWebSocketAddress", "")?
            } else { String::new() };
            let xmr_web_socket_address_in_use = if let Some(forced) = forced_ws {
                log::info!("using AREXIBO_FORCE_WS_ADDRESS override for XMR WebSocket \
                            address, ignoring the CMS's own xmrType/xmrWebSocketAddress \
                            for this registration");
                forced
            } else if &xmr_type == "ws" {
                if !xmr_web_socket_address.is_empty() {
                    xmr_web_socket_address.clone()
                } else if let Some(default) = &self.default_ws_address {
                    // The CMS never computes this default server-side
                    // despite documenting the convention (see
                    // CmsSettings::default_xmr_websocket_address) --
                    // without this, an empty address here always meant
                    // ZMQ, never trying WebSocket for a CMS relying on
                    // this documented default (e.g. Docker with
                    // XMR_WS_ADDRESS left empty).
                    log::debug!("CMS sent an empty XMR WebSocket address (xmrType=ws) -- \
                                trying the documented default convention ({default}, same \
                                host as the CMS itself, path /xmr) before falling back to \
                                ZMQ. See account.xibosignage.com/docs/setup/xibo-for-docker \
                                for the convention this follows.");
                    default.clone()
                } else {
                    String::new()
                }
            } else { String::new() };

            Ok(Some(PlayerSettings {
                // xmrNetworkAddress (legacy ZMQ fallback) can be
                // legitimately absent for a WebSocket-only client --
                // def_child (graceful empty default), not parse_child
                // (hard failure), matching its XMR sibling fields.
                xmr_network_address: tree.def_child("xmrNetworkAddress", "")?,
                xmr_web_socket_address,
                xmr_web_socket_address_in_use,
                xmr_cms_key: tree.def_child("xmrCmsKey", "")?,
                // All fields below are optional with conservative
                // defaults, not mandatory via parse_child -- a real CMS
                // response for some client types (e.g. "windows") omits
                // several of these entirely; treating that as a hard
                // registration failure fell back to stale cached
                // settings unnecessarily.
                log_level: tree.def_child("logLevel", "error".to_string())?,
                display_name: tree.def_child("displayName", self.display_name.clone())?,
                // Xibo's own typical CMS default for Proof of Play stats
                // is enabled; failing closed here (defaulting off) would
                // be surprising, not safe, so default to the CMS's own
                // usual behavior instead.
                stats_enabled: tree.def_child::<i32>("statsEnabled", 1)? != 0,
                prevent_sleep: tree.def_child::<i32>("preventSleep", 0)? != 0,
                // 300s (5 minutes) matches Xibo's own commonly-documented
                // default collection interval.
                collect_interval: tree.def_child("collectInterval", 300u32)?,
                // 0 already means "don't poll for screenshots" elsewhere
                // (see mainloop.rs's `if self.settings.screenshot_interval
                // != 0`) -- safe, inert default.
                screenshot_interval: tree.def_child("screenShotRequestInterval", 0u32)?,
                // FLAGGED AS UNVERIFIED (element name): follows the usual
                // lowerCamelCase-of-the-C#-PascalCase convention
                // (`ScreenShotSize` -> `screenShotSize`), but not
                // independently confirmed against a real ActivationMessage.
                // `def_child` with default 0 fails safe (no resize,
                // today's existing behavior) if the CMS omits it.
                screenshot_size: tree.def_child("screenShotSize", 0u32)?,
                // Same lowerCamelCase convention as every other field
                // here; the C# property name
                // (`SendCurrentLayoutAsStatusUpdate`) is confirmed real
                // (seen directly in MainWindow.xaml.cs, gating the
                // exact same immediate-notify-on-layout-change call
                // this field now gates in mainloop.rs). Defaults to
                // true -- see the field's own doc comment in
                // config.rs for why closed-by-default would be unsafe
                // here specifically.
                send_current_layout_as_status_update:
                    tree.def_child::<i32>("sendCurrentLayoutAsStatusUpdate", 1)? != 0,
                // Same lowerCamelCase convention as every other field
                // here; the C# property name (`IsAdspaceEnabled`) is
                // confirmed real (seen directly in ScheduleManager.cs),
                // but the exact XML element name is FLAGGED AS
                // UNVERIFIED. Fails closed (adspace off) if absent.
                is_adspace_enabled: tree.def_child::<i32>("isAdspaceEnabled", 0)? != 0,
                // BUG fix (found from a real report, confirmed via a
                // real RegisterDisplay response): these are "HH:MM"
                // strings, not plain integers -- see
                // PlayerSettings::is_within_download_window for how
                // they actually get parsed/enforced.
                download_start_window: tree.def_child::<String>("downloadStartWindow",
                                                                  String::new())?,
                download_end_window: tree.def_child::<String>("downloadEndWindow",
                                                                String::new())?,
                display_time_zone: tree.def_child::<String>("displayTimeZone", String::new())?,
                expire_modified_layouts: tree.def_child::<i32>("expireModifiedLayouts", 0)? != 0,
                screen_shot_requested: tree.def_child::<i32>("screenShotRequested", 0)? != 0,
                new_cms_address: tree.def_child::<String>("newCmsAddress", String::new())?,
                new_cms_key: tree.def_child::<String>("newCmsKey", String::new())?,
                force_https: tree.def_child::<i32>("forceHttps", 0)? != 0,
                // embeddedServerPort from the CMS is effectively
                // vestigial regardless -- main.rs immediately overwrites
                // it with whatever port we actually bound locally
                // (`settings.embedded_server_port = webserver.port();`),
                // so any value here (or its absence) has no real effect.
                embedded_server_port: tree.def_child("embeddedServerPort", 0u16)?,
                // 0 already means "use the full screen" for both
                // dimensions (see gui/view.cpp: `if (size_x == 0) size_x
                // = screen_w;`) -- safe, already-established sentinel.
                size_x: tree.def_child("sizeX", 0i32)?,
                size_y: tree.def_child("sizeY", 0i32)?,
                pos_x: tree.def_child("offsetX", 0i32)?,
                pos_y: tree.def_child("offsetY", 0i32)?,
                commands,
                // FLAGGED AS UNVERIFIED: element names follow the same
                // lowerCamelCase-of-the-C#-PascalCase-property convention
                // every other field here already uses (e.g. `preventSleep`
                // for `PreventSleep`), but aren't independently confirmed
                // against a real ActivationMessage response containing
                // them. `def_child` with conservative defaults (shell
                // commands OFF, empty allowlist) means a CMS that omits
                // these entirely fails closed rather than silently
                // enabling arbitrary command execution.
                enable_shell_commands: tree.def_child::<i32>("enableShellCommands", 0)? != 0,
                shell_command_allow_list: tree.def_child("shellCommandAllowList", "")?,
            }))
        }
    }

    pub fn required_files(&mut self) -> Result<(Vec<ReqFile>, Vec<String>)> {
        let xml = self.service.RequiredFiles(
            soap::RequiredFilesRequest {
                serverKey: &self.cms_key,
                hardwareKey: &self.hw_key,
            }
        ).context("getting required files")?.RequiredFilesXml;
        let _ = fs::write(self.xml_dir.join("required.xml"), &xml);

        let tree = Element::from_reader(&mut xml.as_bytes()).context("parsing required files")?;
        let mut res = vec![];
        let mut purge = vec![];
        for file in tree.find_all("file") {
            let typ = file.get_attr("type").context("missing file type")?;
            if typ == "media" || typ == "layout" {
                let http = file.get_attr("download").context("missing download")? == "http";
                let (path, name) = if http {
                    (file.parse_attr("path")?, file.parse_attr("saveAs")?)
                } else {
                    let mut path= file.parse_attr::<String>("path")?;
                    if typ == "layout" {
                        path.push_str(".xlf");
                    }
                    (String::new(), path)
                };
                res.push(ReqFile::File {
                    id: file.parse_attr("id")?,
                    // match seems like a no-op but maps to a &'static str
                    typ: match typ { "media" => "media", "layout" => "layout",
                                      _ => unreachable!() },
                    size: file.parse_attr("size")?,
                    md5: hex::decode(file.parse_attr::<String>("md5")?)?,
                    code: file.get_attr("code").map(Into::into),
                    path, name, http,
                });
            } else if typ == "resource" {
                res.push(ReqFile::Resource {
                    id: file.parse_attr("id")?,
                    layoutid: file.parse_attr("layoutid")?,
                    regionid: file.parse_attr("regionid")?,
                    mediaid: file.parse_attr("mediaid")?,
                    updated: file.parse_attr("updated")?,
                });
            } else if typ == "dependency" {
                // Attributes confirmed via the real reference client
                // source (xibo-dotnetclient's RequiredFiles.cs) -- id
                // is a string (e.g. a font/bundle name), not an int
                // like every other file type, and there is no md5 to
                // verify against (unlike media/layout).
                res.push(ReqFile::Dependency {
                    id: file.parse_attr("id")?,
                    file_type: file.parse_attr("fileType")?,
                    size: file.parse_attr("size")?,
                    http: file.get_attr("download").context("missing download")? == "http",
                    path: file.parse_attr("path")?,
                    name: file.parse_attr("saveAs")?,
                });
            } else {
                continue;
            }
        }
        for subtree in tree.find_all("purge") {
            for item in subtree.find_all("item") {
                if let Some(name) = item.get_attr("storedAs") {
                    purge.push(name.into());
                }
            }
        }
        Ok((res, purge))
    }

    pub fn get_schedule(&mut self) -> Result<Schedule> {
        let xml = self.service.Schedule(
            soap::ScheduleRequest {
                serverKey: &self.cms_key,
                hardwareKey: &self.hw_key,
            }
        ).context("getting schedule")?.ScheduleXml;
        let _ = fs::write(self.xml_dir.join("schedule.xml"), &xml);

        let tree = Element::from_reader(&mut xml.as_bytes()).context("parsing schedule")?;
        Schedule::parse(&tree)
    }

    pub fn get_file_data(&mut self, file: i64, ftype: &str, offset: u64, size: u64) -> Result<Vec<u8>> {
        Ok(self.service.GetFile(
            soap::GetFileRequest {
                serverKey: &self.cms_key,
                hardwareKey: &self.hw_key,
                fileId: file,
                fileType: ftype,
                chunkOffset: offset as f64,
                chuckSize: size as f64,
            }
        ).context("getting file data")?.file.0)
    }

    /// Gets a chunk of a player dependency (e.g. a font, or a player
    /// bundle JS/CSS file used by Elements-based widgets) via the
    /// GetDependency XMDS call -- distinct from GetFile: dependency
    /// ids are strings (e.g. a bundle/font name), not integers, unlike
    /// every other file type. Confirmed via the real reference client
    /// source (xibo-dotnetclient's RequiredFiles.cs) and the real v7
    /// WSDL, neither of which arexibo previously implemented at all --
    /// any RequiredFiles entry with type="dependency" was silently
    /// skipped entirely (see required_files's own handling), so any
    /// widget relying on a player-delivered dependency (fonts for
    /// Elements-based Data Widgets, in particular) could never
    /// actually get it.
    pub fn get_dependency_data(&mut self, id: &str, ftype: &str, offset: u64, size: u64) -> Result<Vec<u8>> {
        Ok(self.service.GetDependency(
            soap::GetDependencyRequest {
                serverKey: &self.cms_key,
                hardwareKey: &self.hw_key,
                fileType: ftype,
                id,
                chunkOffset: offset as f64,
                chunkSize: size as f64,
            }
        ).context("getting dependency data")?.file.0)
    }

    /// Gets the JSON data for an Elements-based Data Widget (e.g. RSS,
    /// social media, weather-via-elements). Confirmed via official
    /// docs (account.xibosignage.com/docs/developer/creating-a-player/
    /// xmds): the returned JSON should be saved as `<widgetId>.json`,
    /// referenced by the widget's own resource HTML via the local
    /// webserver, and may contain a `files` property listing
    /// additional media (always HTTP-downloadable) the data itself
    /// references (e.g. images embedded in an RSS item).
    ///
    /// FLAGGED AS UNVERIFIED / INCOMPLETE: only this raw SOAP call
    /// itself is implemented and confirmed against the real WSDL --
    /// the exact trigger (which RequiredFiles entry, if any, signals
    /// "this widget needs GetData called for it", and how the
    /// resulting JSON's own `files` property is shaped) was not found
    /// in the reference client's own public source during a search,
    /// unlike GetDependency's own RequiredFiles.cs. NOT YET WIRED IN
    /// to any download/collection cycle -- calling this alone doesn't
    /// make Data Widgets work end-to-end yet.
    pub fn get_data(&mut self, widget_id: i64) -> Result<String> {
        Ok(self.service.GetData(
            soap::GetDataRequest {
                serverKey: &self.cms_key,
                hardwareKey: &self.hw_key,
                widgetId: widget_id,
            }
        ).context("getting widget data")?.data)
    }

    /// Gets weather conditions for this display's own location (no
    /// widget/geo params -- the CMS resolves these from the display's
    /// own configuration). Confirmed via the real reference client
    /// source (xibo-dotnetclient's XmdsAgents/WeatherAgent.cs): this
    /// does NOT feed widget rendering at all -- every key/value pair
    /// in the returned JSON becomes a Schedule Criteria update (same
    /// destination as the existing xmr::Message::CriteriaUpdate push
    /// mechanism, just pulled periodically instead of pushed by the
    /// CMS). Called once per collection cycle in the reference client
    /// (not on its own independent timer, unlike GetData's own
    /// DataAgent), gated behind a simple enabled/disabled toggle
    /// there -- FLAGGED AS UNVERIFIED here: the exact signal for when
    /// weather is "required" for a given display wasn't confirmed:
    /// called unconditionally instead, once per collection cycle
    /// (see mainloop.rs's own collect_once), matching the reference
    /// client's own polling cadence when enabled.
    pub fn get_weather(&mut self) -> Result<String> {
        Ok(self.service.GetWeather(
            soap::GetWeatherRequest {
                serverKey: &self.cms_key,
                hardwareKey: &self.hw_key,
            }
        ).context("getting weather")?.data)
    }

    pub fn get_resource(&mut self, layout: i64, region: &str, media: &str) -> Result<String> {
        Ok(self.service.GetResource(
            soap::GetResourceRequest {
                serverKey: &self.cms_key,
                hardwareKey: &self.hw_key,
                layoutId: layout,
                regionId: region,
                mediaId: media,
            }
        ).context("getting resource")?.resource)
    }

    pub fn blacklist(&mut self, media: i64, mtype: &str, reason: &str) -> Result<()> {
        let res = self.service.BlackList(
            soap::BlackListRequest {
                serverKey: &self.cms_key,
                hardwareKey: &self.hw_key,
                mediaId: media,
                r#type: mtype,
                reason,
            }
        ).context("blacklisting media")?;
        ensure!(res.success, "blacklisting not successful");
        Ok(())
    }

    pub fn submit_media_inventory(&mut self, inv: Vec<((&'static str, i64), bool)>) -> Result<()> {
        let mut files = Element::new("files");
        for ((typ, id), complete) in inv {
            let mut file = Element::new("file");
            file.set_attr("type", typ);
            file.set_attr("id", id.to_string());
            file.set_attr("complete", if complete { "1" } else { "0" });
            files.append_child(file);
        }

        let inv_xml = format!("<![CDATA[{}]]>", files.to_string()?);
        let res = self.service.MediaInventory(
            soap::MediaInventoryRequest {
                serverKey: &self.cms_key,
                hardwareKey: &self.hw_key,
                mediaInventory: &inv_xml,
            }
        ).context("submitting media inventory")?;
        ensure!(res.success, "submitting inventory not successful");
        Ok(())
    }

    pub fn submit_log(&mut self, entries: &[LogEntry]) -> Result<()> {
        let mut logs = Element::new("logs");
        for entry in entries {
            let mut log = Element::new("log");
            log.set_attr("date", entry.date.format(&TIME_FMT).expect("time fmt"));
            log.set_attr("category", entry.category);
            log.append_child(Element::new("message")).set_text(&entry.message);
            logs.append_child(log);
        }

        let log_xml = format!("<![CDATA[{}]]>", logs.to_string()?);
        let res = self.service.SubmitLog(
            soap::SubmitLogRequest {
                serverKey: &self.cms_key,
                hardwareKey: &self.hw_key,
                logXml: &log_xml
            }
        ).context("submitting logs")?;
        ensure!(res.success, "submitting logs not successful");
        Ok(())
    }

    pub fn submit_stats(&mut self, stat_xml: &str) -> Result<()> {
        // Wrapped in CDATA for the same reason submit_log/
        // submit_media_inventory above already do this: statXml's value
        // is itself an XML fragment (`<stats>...</stats>`), and embedding
        // it unescaped/unwrapped as a plain xsd:string parameter makes it
        // parse as literal child elements of the SOAP body instead of
        // text content -- well-formed XML overall, but a WSDL type
        // violation that a real CMS was observed to reject outright with
        // "SOAP-ERROR: Encoding: Violation of encoding rules". This was
        // missing here even though the exact same problem was already
        // solved for the two sibling calls above -- inconsistency, not a
        // deliberate difference.
        let stat_xml = format!("<![CDATA[{stat_xml}]]>");
        let res = self.service.SubmitStats(
            soap::SubmitStatsRequest {
                serverKey: &self.cms_key,
                hardwareKey: &self.hw_key,
                statXml: &stat_xml
            }
        ).context("submitting stats")?;
        ensure!(res.success, "submitting stats not successful");
        Ok(())
    }

    /// Report Player faults (XMDS v6+, faults.rs). `faults_json` is a
    /// JSON array (see faults.rs's doc comment for the confirmed
    /// payload shape). Wrapped in CDATA for the same reason as
    /// submit_stats above -- JSON doesn't normally contain XML-unsafe
    /// characters, but a fault's own `reason` text plausibly could (an
    /// error message quoting a `<tag>`, for instance), and this is cheap
    /// insurance against repeating today's SubmitStats encoding bug.
    pub fn report_faults(&mut self, faults_json: &str) -> Result<()> {
        let wrapped = format!("<![CDATA[{faults_json}]]>");
        let res = self.service.ReportFaults(
            soap::ReportFaultsRequest {
                serverKey: &self.cms_key,
                hardwareKey: &self.hw_key,
                faults: &wrapped,
            }
        ).context("reporting faults")?;
        ensure!(res.success, "reporting faults not successful");
        Ok(())
    }

    pub fn submit_screenshot(&mut self, shot: Vec<u8>) -> Result<()> {
        let res = self.service.SubmitScreenShot(
            soap::SubmitScreenShotRequest {
                serverKey: &self.cms_key,
                hardwareKey: &self.hw_key,
                screenShot: Base64Field(shot),
            }
        ).context("submitting screenshot")?;
        ensure!(res.success, "submitting screenshot not successful");
        Ok(())
    }

    pub fn notify_command_success(&mut self, result: bool) -> Result<()> {
        self.notify_status_raw(&format!("{{\"lastCommandSuccess\": {result}}}"))
    }

    pub fn notify_status(&mut self, status: &Status<'_>) -> Result<()> {
        self.notify_status_raw(&serde_json::to_string(status)?)
    }

    fn notify_status_raw(&mut self, status: &str) -> Result<()> {
        let res = self.service.NotifyStatus(
            soap::NotifyStatusRequest {
                serverKey: &self.cms_key,
                hardwareKey: &self.hw_key,
                status,
            }
        ).context("notifying status")?;
        ensure!(res.success, "status notification not successful");
        Ok(())
    }
}

#[allow(non_snake_case)]
#[derive(Serialize)]
pub struct Status<'s> {
    pub currentLayoutId: i64,
    pub availableSpace: u64,
    pub totalSpace: u64,
    pub lastCommandSuccess: bool,
    pub deviceName: &'s str,
    pub timeZone: &'s str,
    // pub latitude: f64,
    // pub longitude: f64,
}



#[cfg(test)]
mod force_ws_address_tests {
    use super::*;
    use std::sync::{Mutex, OnceLock};

    // Serializes access to the env var across tests in this module --
    // std::env::set_var affects the whole process, and cargo test runs
    // tests in parallel by default, so two tests touching this var at
    // once could otherwise interfere with each other.
    fn env_lock() -> &'static Mutex<()> {
        static LOCK: OnceLock<Mutex<()>> = OnceLock::new();
        LOCK.get_or_init(|| Mutex::new(()))
    }

    /// Minimal mock XMDS server, returning a controllable
    /// RegisterDisplay response -- verified against the real generated
    /// SOAP response parser (target/.../out/xmds_soap.rs), same
    /// approach as mainloop.rs's own pending_auth_tests.
    fn start_mock(xmr_type: &str, xmr_ws_address: &str) -> u16 {
        let server = tiny_http::Server::http("127.0.0.1:0").unwrap();
        let port = server.server_addr().to_ip().unwrap().port();
        let activation = format!(
            r#"<ActivationMessage code="READY"><xmrType>{xmr_type}</xmrType><xmrWebSocketAddress>{xmr_ws_address}</xmrWebSocketAddress></ActivationMessage>"#);
        let escaped = activation.replace('&', "&amp;").replace('<', "&lt;")
                                 .replace('>', "&gt;").replace('"', "&quot;");
        std::thread::spawn(move || {
            for request in server.incoming_requests() {
                let body = format!(
                    r#"<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
<soap:Body><RegisterDisplayResponse><ActivationMessage>{escaped}</ActivationMessage></RegisterDisplayResponse></soap:Body>
</soap:Envelope>"#);
                let _ = request.respond(tiny_http::Response::from_string(body));
            }
        });
        port
    }

    fn test_cms(port: u16) -> Cms {
        let cms_settings = crate::config::CmsSettings {
            address: format!("http://127.0.0.1:{port}"),
            key: "testkey".into(),
            display_id: "test-display".into(),
            display_name: None,
            proxy: None,
        };
        let xml_dir = std::env::temp_dir().join(format!(
            "arexibo_force_ws_test_{}_{}", std::process::id(),
            std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap().as_nanos()));
        std::fs::create_dir_all(&xml_dir).unwrap();
        Cms::new(&cms_settings, "dummy-pub-key".into(), true, xml_dir).unwrap()
    }

    #[test]
    fn cms_reported_zmq_normally_clears_the_ws_address() {
        // Baseline, confirming the existing (section 59/64) behavior
        // is unaffected when no override is set: xmrType != "ws" means
        // an empty WebSocket address, exactly as before.
        let _guard = env_lock().lock().unwrap();
        std::env::remove_var("AREXIBO_FORCE_WS_ADDRESS");
        let port = start_mock("zmq", "ws://192.168.2.10:8080");
        let mut cms = test_cms(port);
        let settings = cms.register_display().unwrap().unwrap();
        assert_eq!(settings.xmr_web_socket_address, "",
                   "must be empty when the CMS reports xmrType=zmq, matching existing behavior");
    }

    #[test]
    fn force_override_wins_even_when_cms_reports_zmq() {
        // The actual feature: a real report showed the CMS
        // inconsistently/consistently reporting xmrType=zmq (wiping a
        // manually-fixed WebSocket address on every single
        // registration) -- this override must make the address stick
        // regardless of what the CMS says on any given call.
        let _guard = env_lock().lock().unwrap();
        std::env::set_var("AREXIBO_FORCE_WS_ADDRESS", "ws://forced.example:9999");
        let port = start_mock("zmq", "ws://192.168.2.10:8080");
        let mut cms = test_cms(port);
        let settings = cms.register_display().unwrap().unwrap();
        std::env::remove_var("AREXIBO_FORCE_WS_ADDRESS");
        assert_eq!(settings.xmr_web_socket_address_in_use, "ws://forced.example:9999",
                   "the override must win, ignoring the CMS's own xmrType=zmq entirely");
        assert_eq!(settings.xmr_web_socket_address, "",
                   "the raw field must still reflect the CMS's own xmrType=zmq (empty), \
                    independent of the override -- it never came from the CMS itself");
    }

    #[test]
    fn force_override_also_wins_when_cms_reports_ws() {
        // Even when the CMS *does* correctly report "ws" with some
        // address, an explicit override should still take precedence
        // -- consistent, predictable behavior regardless of what the
        // CMS happens to say on any given call, not just when it's
        // "wrong".
        let _guard = env_lock().lock().unwrap();
        std::env::set_var("AREXIBO_FORCE_WS_ADDRESS", "ws://forced.example:9999");
        let port = start_mock("ws", "ws://192.168.2.10:8080");
        let mut cms = test_cms(port);
        let settings = cms.register_display().unwrap().unwrap();
        std::env::remove_var("AREXIBO_FORCE_WS_ADDRESS");
        assert_eq!(settings.xmr_web_socket_address_in_use, "ws://forced.example:9999");
        assert_eq!(settings.xmr_web_socket_address, "ws://192.168.2.10:8080",
                   "the raw field must still reflect what the CMS actually sent, \
                    independent of the override winning for the in-use address");
    }

    #[test]
    fn empty_override_value_is_treated_as_unset() {
        // AREXIBO_FORCE_WS_ADDRESS="" (set but empty -- e.g. from a
        // shell script that exports an unfilled variable) must behave
        // exactly as if it were never set at all, not as "force an
        // empty address" (which would be indistinguishable from the
        // CMS's own zmq case, but for a confusingly different reason).
        let _guard = env_lock().lock().unwrap();
        std::env::set_var("AREXIBO_FORCE_WS_ADDRESS", "");
        let port = start_mock("ws", "ws://192.168.2.10:8080");
        let mut cms = test_cms(port);
        let settings = cms.register_display().unwrap().unwrap();
        std::env::remove_var("AREXIBO_FORCE_WS_ADDRESS");
        assert_eq!(settings.xmr_web_socket_address_in_use, "ws://192.168.2.10:8080",
                   "an empty override value must fall through to the CMS's own reported address");
    }
}

#[cfg(test)]
mod default_ws_address_fallback_tests {
    use super::*;

    /// Same mock pattern as force_ws_address_tests, duplicated locally
    /// (not shared) so this module's own tests read standalone.
    fn start_mock(xmr_type: &str, xmr_ws_address: &str) -> u16 {
        let server = tiny_http::Server::http("127.0.0.1:0").unwrap();
        let port = server.server_addr().to_ip().unwrap().port();
        let activation = format!(
            r#"<ActivationMessage code="READY"><xmrType>{xmr_type}</xmrType><xmrWebSocketAddress>{xmr_ws_address}</xmrWebSocketAddress></ActivationMessage>"#);
        let escaped = activation.replace('&', "&amp;").replace('<', "&lt;")
                                 .replace('>', "&gt;").replace('"', "&quot;");
        std::thread::spawn(move || {
            for request in server.incoming_requests() {
                let body = format!(
                    r#"<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
<soap:Body><RegisterDisplayResponse><ActivationMessage>{escaped}</ActivationMessage></RegisterDisplayResponse></soap:Body>
</soap:Envelope>"#);
                let _ = request.respond(tiny_http::Response::from_string(body));
            }
        });
        port
    }

    fn test_cms(port: u16) -> Cms {
        let cms_settings = crate::config::CmsSettings {
            address: format!("http://127.0.0.1:{port}"),
            key: "testkey".into(),
            display_id: "test-display".into(),
            display_name: None,
            proxy: None,
        };
        let xml_dir = std::env::temp_dir().join(format!(
            "arexibo_default_ws_test_{}_{}", std::process::id(),
            std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap().as_nanos()));
        std::fs::create_dir_all(&xml_dir).unwrap();
        Cms::new(&cms_settings, "dummy-pub-key".into(), true, xml_dir).unwrap()
    }

    #[test]
    fn empty_address_with_ws_type_falls_back_to_the_derived_default() {
        // The actual feature this module tests: found from a real
        // user's own suspicion, confirmed against the real CMS source
        // (lib/Xmds/Soap5.php) AND the official Docker docs -- an
        // empty xmrWebSocketAddress with xmrType=ws (matching, e.g., a
        // fresh Docker install with XMR_WS_ADDRESS left at its own
        // documented default, empty, value) must fall back to
        // ws://<same host:port as the CMS>/xmr, not straight to empty
        // (which previously meant giving up on WebSocket XMR entirely,
        // falling straight to ZMQ).
        let port = start_mock("ws", "");
        let mut cms = test_cms(port);
        let settings = cms.register_display().unwrap().unwrap();
        assert_eq!(settings.xmr_web_socket_address_in_use, format!("ws://127.0.0.1:{port}/xmr"),
                   "must fall back to the derived default when the CMS sends an empty \
                    address with xmrType=ws");
        assert_eq!(settings.xmr_web_socket_address, "",
                   "the raw field must stay empty -- the CMS genuinely sent nothing, \
                    the derived default is a local fallback, not something the CMS itself sent");
    }

    #[test]
    fn a_real_non_empty_address_from_the_cms_always_wins_over_the_default() {
        // The derived default must never override a genuine, non-empty
        // address the CMS actually sends -- it's strictly a last-resort
        // fallback for the empty case specifically.
        let port = start_mock("ws", "ws://192.168.2.10:8080");
        let mut cms = test_cms(port);
        let settings = cms.register_display().unwrap().unwrap();
        assert_eq!(settings.xmr_web_socket_address_in_use, "ws://192.168.2.10:8080",
                   "a real address from the CMS must always win over the derived default");
        assert_eq!(settings.xmr_web_socket_address, "ws://192.168.2.10:8080",
                   "the raw field must match exactly what the CMS actually sent");
    }

    #[test]
    fn zmq_type_never_triggers_the_default_even_if_address_is_empty() {
        // The derived default is specifically for xmrType=ws -- if the
        // CMS says zmq, an empty address must stay empty exactly as
        // before (section 59/64's own existing behavior), not suddenly
        // start trying a derived WebSocket URL the CMS never asked for.
        let port = start_mock("zmq", "");
        let mut cms = test_cms(port);
        let settings = cms.register_display().unwrap().unwrap();
        assert_eq!(settings.xmr_web_socket_address_in_use, "",
                   "must stay empty for xmrType=zmq, regardless of the derived default \
                    being available");
    }
}

#[cfg(test)]
mod required_files_dependency_tests {
    use super::*;

    /// Mock XMDS server: responds to every request with the given
    /// RequiredFilesXml body -- Cms::new() itself makes no network
    /// call (unlike mainloop::Handler::new()), so the first request
    /// this test's own required_files() call makes is already the
    /// RequiredFiles one.
    fn start_mock(required_files_xml: &'static str) -> u16 {
        let server = tiny_http::Server::http("127.0.0.1:0").unwrap();
        let port = server.server_addr().to_ip().unwrap().port();
        std::thread::spawn(move || {
            for request in server.incoming_requests() {
                let escaped = required_files_xml.replace('&', "&amp;").replace('<', "&lt;")
                                                 .replace('>', "&gt;").replace('"', "&quot;");
                let body = format!(
                    r#"<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
<soap:Body><RequiredFilesResponse><RequiredFilesXml>{escaped}</RequiredFilesXml></RequiredFilesResponse></soap:Body>
</soap:Envelope>"#);
                let _ = request.respond(tiny_http::Response::from_string(body));
            }
        });
        port
    }

    fn test_cms(port: u16) -> Cms {
        let cms_settings = crate::config::CmsSettings {
            address: format!("http://127.0.0.1:{port}"),
            key: "testkey".into(),
            display_id: "test-display".into(),
            display_name: None,
            proxy: None,
        };
        let xml_dir = std::env::temp_dir().join(format!(
            "arexibo_dependency_test_{}_{}", std::process::id(),
            std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap().as_nanos()));
        std::fs::create_dir_all(&xml_dir).unwrap();
        Cms::new(&cms_settings, "dummy-pub-key".into(), true, xml_dir).unwrap()
    }

    #[test]
    fn a_dependency_entry_is_parsed_not_silently_skipped() {
        // Regression test: previously, any RequiredFiles <file> entry
        // with a type other than media/layout/resource was silently
        // discarded via `continue` -- confirmed via the real reference
        // client source (xibo-dotnetclient's RequiredFiles.cs) that
        // "dependency" is a real, distinct file type the CMS sends,
        // with its own attribute set (id as a string, fileType as an
        // inner sub-type, no md5).
        let xml = r#"<files>
            <file type="dependency" id="roboto-regular.ttf" fileType="font"
                  size="12345" download="xmds" path="/fonts/roboto-regular.ttf"
                  saveAs="roboto-regular.ttf"/>
        </files>"#;
        let port = start_mock(xml);
        let mut cms = test_cms(port);
        let (files, _purge) = cms.required_files().unwrap();
        assert_eq!(files.len(), 1, "the dependency entry must not be silently skipped");
        match &files[0] {
            ReqFile::Dependency { id, file_type, size, http, path, name } => {
                assert_eq!(id, "roboto-regular.ttf");
                assert_eq!(file_type, "font");
                assert_eq!(*size, 12345);
                assert!(!http);
                assert_eq!(path, "/fonts/roboto-regular.ttf");
                assert_eq!(name, "roboto-regular.ttf");
            }
            other => panic!("expected ReqFile::Dependency, got a different variant: {other:?}"),
        }
    }

    #[test]
    fn a_dependency_entry_over_http_is_parsed_correctly() {
        let xml = r#"<files>
            <file type="dependency" id="player-bundle.js" fileType="playerBundle"
                  size="999" download="http" path="https://cms.example/bundle.js"
                  saveAs="player-bundle.js"/>
        </files>"#;
        let port = start_mock(xml);
        let mut cms = test_cms(port);
        let (files, _purge) = cms.required_files().unwrap();
        assert_eq!(files.len(), 1);
        match &files[0] {
            ReqFile::Dependency { http, path, .. } => {
                assert!(*http, "download=\"http\" must be parsed as the http download path");
                assert_eq!(path, "https://cms.example/bundle.js");
            }
            other => panic!("expected ReqFile::Dependency, got a different variant: {other:?}"),
        }
    }

    #[test]
    fn media_and_dependency_entries_coexist_correctly() {
        // Guards against a regression that would misclassify one type
        // as the other, or lose one of them, when both appear together
        // (the realistic case -- a Data Widget's own media alongside
        // its font dependency).
        let xml = r#"<files>
            <file type="media" id="42" size="100" md5="d41d8cd98f00b204e9800998ecf8427e"
                  download="xmds" path="" saveAs="42.jpg"/>
            <file type="dependency" id="roboto-regular.ttf" fileType="font"
                  size="12345" download="xmds" path="/fonts/roboto-regular.ttf"
                  saveAs="roboto-regular.ttf"/>
        </files>"#;
        let port = start_mock(xml);
        let mut cms = test_cms(port);
        let (files, _purge) = cms.required_files().unwrap();
        assert_eq!(files.len(), 2);
        assert!(matches!(&files[0], ReqFile::File { typ: "media", .. }));
        assert!(matches!(&files[1], ReqFile::Dependency { .. }));
    }
}

#[cfg(test)]
mod get_dependency_data_tests {
    use super::*;

    fn start_mock(response_bytes: &'static [u8]) -> u16 {
        let server = tiny_http::Server::http("127.0.0.1:0").unwrap();
        let port = server.server_addr().to_ip().unwrap().port();
        std::thread::spawn(move || {
            for request in server.incoming_requests() {
                use base64::Engine as _;
                let encoded = base64::engine::general_purpose::STANDARD.encode(response_bytes);
                let body = format!(
                    r#"<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
<soap:Body><GetDependencyResponse><file>{encoded}</file></GetDependencyResponse></soap:Body>
</soap:Envelope>"#);
                let _ = request.respond(tiny_http::Response::from_string(body));
            }
        });
        port
    }

    fn test_cms(port: u16) -> Cms {
        let cms_settings = crate::config::CmsSettings {
            address: format!("http://127.0.0.1:{port}"),
            key: "testkey".into(),
            display_id: "test-display".into(),
            display_name: None,
            proxy: None,
        };
        let xml_dir = std::env::temp_dir().join(format!(
            "arexibo_getdep_test_{}_{}", std::process::id(),
            std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap().as_nanos()));
        std::fs::create_dir_all(&xml_dir).unwrap();
        Cms::new(&cms_settings, "dummy-pub-key".into(), true, xml_dir).unwrap()
    }

    #[test]
    fn fetches_a_dependency_chunk_by_its_string_id() {
        // Confirms the actual SOAP round-trip works end-to-end
        // (request built correctly, response parsed correctly) for a
        // real, non-numeric dependency id -- not just that the WSDL
        // compiles.
        let port = start_mock(b"font file bytes here");
        let mut cms = test_cms(port);
        let data = cms.get_dependency_data("roboto-regular.ttf", "font", 0, 1024).unwrap();
        assert_eq!(data, b"font file bytes here");
    }
}

#[cfg(test)]
mod get_data_tests {
    use super::*;

    fn start_mock(response_json: &'static str) -> u16 {
        let server = tiny_http::Server::http("127.0.0.1:0").unwrap();
        let port = server.server_addr().to_ip().unwrap().port();
        std::thread::spawn(move || {
            for request in server.incoming_requests() {
                let escaped = response_json.replace('&', "&amp;").replace('<', "&lt;")
                                            .replace('>', "&gt;").replace('"', "&quot;");
                let body = format!(
                    r#"<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
<soap:Body><GetDataResponse><data>{escaped}</data></GetDataResponse></soap:Body>
</soap:Envelope>"#);
                let _ = request.respond(tiny_http::Response::from_string(body));
            }
        });
        port
    }

    fn test_cms(port: u16) -> Cms {
        let cms_settings = crate::config::CmsSettings {
            address: format!("http://127.0.0.1:{port}"),
            key: "testkey".into(),
            display_id: "test-display".into(),
            display_name: None,
            proxy: None,
        };
        let xml_dir = std::env::temp_dir().join(format!(
            "arexibo_getdata_test_{}_{}", std::process::id(),
            std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap().as_nanos()));
        std::fs::create_dir_all(&xml_dir).unwrap();
        Cms::new(&cms_settings, "dummy-pub-key".into(), true, xml_dir).unwrap()
    }

    #[test]
    fn fetches_widget_data_by_its_integer_widget_id() {
        // Confirms the SOAP round-trip works for a real, non-trivial
        // JSON payload (not just that the WSDL compiles) -- widgetId
        // is an int here, unlike GetDependency's own string id.
        let port = start_mock(r#"{"data":[{"title":"hello"}],"files":[]}"#);
        let mut cms = test_cms(port);
        let data = cms.get_data(42).unwrap();
        assert_eq!(data, r#"{"data":[{"title":"hello"}],"files":[]}"#);
    }
}

#[cfg(test)]
mod xmds_supports_v6_v7_methods_tests {
    use super::*;

    #[test]
    fn correctly_reflects_the_current_hardcoded_endpoint_version() {
        // Trip-wire: if XMDS_ENDPOINT_VERSION is bumped, re-read its
        // doc comment before updating this expected value.
        assert!(!xmds_supports_v6_v7_methods());
    }
}

#[cfg(test)]
mod get_weather_tests {
    use super::*;

    fn start_mock(response_json: &'static str) -> u16 {
        let server = tiny_http::Server::http("127.0.0.1:0").unwrap();
        let port = server.server_addr().to_ip().unwrap().port();
        std::thread::spawn(move || {
            for request in server.incoming_requests() {
                let escaped = response_json.replace('&', "&amp;").replace('<', "&lt;")
                                            .replace('>', "&gt;").replace('"', "&quot;");
                let body = format!(
                    r#"<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
<soap:Body><GetWeatherResponse><data>{escaped}</data></GetWeatherResponse></soap:Body>
</soap:Envelope>"#);
                let _ = request.respond(tiny_http::Response::from_string(body));
            }
        });
        port
    }

    fn test_cms(port: u16) -> Cms {
        let cms_settings = crate::config::CmsSettings {
            address: format!("http://127.0.0.1:{port}"),
            key: "testkey".into(),
            display_id: "test-display".into(),
            display_name: None,
            proxy: None,
        };
        let xml_dir = std::env::temp_dir().join(format!(
            "arexibo_getweather_test_{}_{}", std::process::id(),
            std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap().as_nanos()));
        std::fs::create_dir_all(&xml_dir).unwrap();
        Cms::new(&cms_settings, "dummy-pub-key".into(), true, xml_dir).unwrap()
    }

    #[test]
    fn fetches_weather_for_this_display_no_extra_params() {
        // Confirms the SOAP round-trip works -- no widgetId/geo params,
        // unlike GetData/GetDependency, matching the confirmed real
        // WSDL shape (serverKey/hardwareKey only).
        let port = start_mock(r#"{"temperature":25,"weather_condition":"clear"}"#);
        let mut cms = test_cms(port);
        let data = cms.get_weather().unwrap();
        assert_eq!(data, r#"{"temperature":25,"weather_condition":"clear"}"#);
    }
}

#[cfg(test)]
mod send_current_layout_as_status_update_parsing_tests {
    use super::*;

    fn start_mock(activation_body: &'static str) -> u16 {
        let server = tiny_http::Server::http("127.0.0.1:0").unwrap();
        let port = server.server_addr().to_ip().unwrap().port();
        std::thread::spawn(move || {
            for request in server.incoming_requests() {
                let escaped = activation_body.replace('&', "&amp;").replace('<', "&lt;")
                                              .replace('>', "&gt;").replace('"', "&quot;");
                let body = format!(
                    r#"<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
<soap:Body><RegisterDisplayResponse><ActivationMessage>{escaped}</ActivationMessage></RegisterDisplayResponse></soap:Body>
</soap:Envelope>"#);
                let _ = request.respond(tiny_http::Response::from_string(body));
            }
        });
        port
    }

    fn test_cms(port: u16) -> Cms {
        let cms_settings = crate::config::CmsSettings {
            address: format!("http://127.0.0.1:{port}"),
            key: "testkey".into(),
            display_id: "test-display".into(),
            display_name: None,
            proxy: None,
        };
        let xml_dir = std::env::temp_dir().join(format!(
            "arexibo_sendlayout_test_{}_{}", std::process::id(),
            std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap().as_nanos()));
        std::fs::create_dir_all(&xml_dir).unwrap();
        Cms::new(&cms_settings, "dummy-pub-key".into(), true, xml_dir).unwrap()
    }

    #[test]
    fn explicit_false_from_the_cms_is_respected() {
        let port = start_mock(
            r#"<ActivationMessage code="READY"><sendCurrentLayoutAsStatusUpdate>0</sendCurrentLayoutAsStatusUpdate></ActivationMessage>"#);
        let mut cms = test_cms(port);
        let settings = cms.register_display().unwrap().unwrap();
        assert!(!settings.send_current_layout_as_status_update);
    }

    #[test]
    fn explicit_true_from_the_cms_is_respected() {
        let port = start_mock(
            r#"<ActivationMessage code="READY"><sendCurrentLayoutAsStatusUpdate>1</sendCurrentLayoutAsStatusUpdate></ActivationMessage>"#);
        let mut cms = test_cms(port);
        let settings = cms.register_display().unwrap().unwrap();
        assert!(settings.send_current_layout_as_status_update);
    }

    #[test]
    fn defaults_to_true_when_the_cms_omits_it() {
        // See the field's own doc comment in config.rs for why this
        // must default to true, not false -- a CMS that simply omits
        // this element must not silently regress back to the laggy
        // "Current Layout" display bug this setting was found for.
        let port = start_mock(r#"<ActivationMessage code="READY"></ActivationMessage>"#);
        let mut cms = test_cms(port);
        let settings = cms.register_display().unwrap().unwrap();
        assert!(settings.send_current_layout_as_status_update);
    }
}
